import { MigrationInterface, QueryRunner } from "typeorm";

export class addAutoGeneratedEvent1685004553896 implements MigrationInterface {
    name = 'addAutoGeneratedEvent1685004553896'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "events" ADD "is_auto_generated" boolean DEFAULT false`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "events" DROP COLUMN "is_auto_generated"`);
    }

}
