import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

import { RecurringType } from '../../../constants/recurring-type';
import {
  BooleanField,
  BooleanFieldOptional,
  DateFieldOptional,
  EnumField,
  EnumFieldOptional,
  IsBehind,
  IsFutureDate,
  IsNullable,
  NumberFieldOptional,
  StringField,
  UUIDFieldOptional,
} from '../../../decorators';
import { WeekDayType } from '../../../modules/event/types/event.type';
import type { ActionPlanType } from '../types/action-plan.type';
import { TodoType } from '../types/todo.type';

export class CreateTodoDto {
  @ApiProperty({ enum: TodoType })
  @EnumField(() => TodoType)
  type: TodoType;

  @ApiProperty()
  @StringField()
  text: string;

  @ApiProperty()
  @BooleanField()
  isDone: boolean;

  @ApiProperty({
    example: ['53f9fc2e-c72e-40fa-8619-6988a42cd4d9'],
    isArray: true,
  })
  @UUIDFieldOptional({ each: true })
  assigneeIds: Uuid[];

  // todo: Deprecated
  @ApiProperty({
    example: '53f9fc2e-c72e-40fa-8619-6988a42cd4d9',
    deprecated: true,
  })
  @UUIDFieldOptional()
  assigneeId?: Uuid;

  @ApiPropertyOptional({ example: new Date(), nullable: true })
  @IsNullable()
  @DateFieldOptional()
  @IsFutureDate()
  dueDate?: Date;

  @ApiPropertyOptional({ example: 4 })
  @NumberFieldOptional({ int: true, min: 0, max: 5 })
  award: number;

  @ApiProperty({ example: '53f9fc2e-c72e-40fa-8619-6988a42cd4d9' })
  @IsNullable()
  @UUIDFieldOptional()
  categoryId?: Uuid;

  @ApiProperty()
  @BooleanFieldOptional()
  byGpt?: boolean;

  @ApiProperty()
  @BooleanFieldOptional()
  isRecurring?: boolean;

  @EnumFieldOptional(() => RecurringType)
  @IsNullable()
  recurringType?: RecurringType;

  @DateFieldOptional()
  @IsNullable()
  @IsBehind('dueDate', {
    message: 'must be behind dueDate',
  })
  untilDateTime?: Date;

  @EnumFieldOptional(() => WeekDayType, { isArray: true, each: true })
  byWeekDay?: WeekDayType[];
}

// use to create default task
// use to internal
export class CreateAutoGeneratedTodoDto extends CreateTodoDto {
  isAutoGenerated: boolean;

  actionPlan: ActionPlanType;
}
