import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';

import { ScheduleService } from '../../shared/services/schedule.service';
import { CreateAutoGeneratedTaskHandler } from './commands/create-auto-generated-task.command';
import { FindOneCategoryHandler } from './commands/find-one-category.command';
import { FinishAutoGeneratedTaskHandler } from './commands/finish-auto-generated-task.command';
import { TodoEntity } from './entities/todo.entity';
import { TodoCategoryEntity } from './entities/todo-category.entity';
import { TodoController } from './todo.controller';
import { TodoCron } from './todo.cron';
import { TodoService } from './todo.service';
import { TodoCategoriesController } from './todo-categories.controller';
import { TodoCategoriesService } from './todo-categories.service';

export const handlers = [
  CreateAutoGeneratedTaskHandler,
  FinishAutoGeneratedTaskHandler,
  FindOneCategoryHandler,
];

@Module({
  imports: [TypeOrmModule.forFeature([TodoEntity, TodoCategoryEntity])],
  controllers: [TodoController, TodoCategoriesController],
  providers: [
    ...handlers,
    TodoService,
    ScheduleService,
    TodoCron,
    TodoCategoriesService,
  ],
})
export class TodoModule {}
