#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged

readonly BRANCH_NAME=$(git branch --show-current)
readonly IMPORTANT_BRANCHES="master main develop"

for BRANCH in $IMPORTANT_BRANCHES; do
    if [ "$BRANCH_NAME" = $BRANCH ]; then
        echo
        echo "Aborting commit."
        echo "You're committing to the $BRANCH branch, usually this is not what you want to do."
        echo "Did you forget to make a new feature branch to put your work on?"
        echo
        echo "Use git checkout -b <new_branch> to create a new feature branch."
        echo
        echo "If you're sure you want to commit to the $BRANCH branch, run git commit with the --no-verify flag."
        echo

        exit 1
    fi
done

echo "Committing on branch $BRANCH_NAME"